encoder_type: "cnn_based"
grid_embedding_dim: 128
network_configs:
  input_dim: 10
  grid_size: [5,5]
  cnn_output_dim: 128
  layer_dims: [16,32,64,128]
  kernel_size: 4
  is_norm: True
  activation: "ReLU"
action_embedding_dim: 1536